### ISSUE TITLE
media type of registration payload

### ISSUE THREAD

**Issue by muoren** [lwmqn/mqtt-shepherd#3]
Hi,
The OMA LWM2M enabler specifies that (see section 5.3.1):

> The payload Media-Type of that registration message MUST be the Core Link Format 
> (application/link-format) defined in [RFC6690]

It looks like here [msghandler.js#L464] you are assuming a JSON object like e.g. `{ oid1: [iid1, iid2], oid2: [iid1] }`, why not use core link format?

[msghandler.js#L464]: https://github.com/lwmqn/mqtt-shepherd/blob/master/lib/components/msghandler.js#L464

Thanks!

**Comment by simenkid** [comment]
Hello,

I abstract all messages with JSON objects for the interfaces that I think it could be easier for me to implement the **_LWM2M-like_** interfaces, it seems no need for me to implement the CoRE on top of MQTT. (Here is indeed a [pub/sub draft](https://tools.ietf.org/html/draft-koster-core-coap-pubsub-05) to define interfaces with CoRE.)

My project is trying to do something to help developers manage the machine network with less effort (especially for a small local area network), and not trying to implement the whole LWM2M thing. I am doing it alone, and I choose to do it with my way (fast and effective :P ).

I had some discussion on LWMQN model with whom doing the pub/sub spec. The manuscript is under revising at this moment, and I will release it open in the near future. 

![lwmqn_model](https://cloud.githubusercontent.com/assets/7709608/17540539/8e3c71e8-5ee9-11e6-8cc9-3bad12e2c899.jpg)

**Comment by muoren** [comment]
Hi,
Thanks for the detailed reply, it would be nice to have that table somewhere in the source or wiki :)

A bit off-topic but this messages could be named and typed e.g. with a TypeScript interface:
```ts
export interface RootObject {
    oid: number;
    iid: number[];
}
```
Or even a JSON schema:

```json
{
  "$schema": "http://json-schema.org/draft-04/schema#",
  "type": "object",
  "properties": {
    "oid": {
      "type": "integer"
    },
    "iid": {
      "type": "array",
      "items": {
        "type": "integer"
      }
    }
  },
  "required": [
    "oid",
    "iid"
  ]
}
```

This is by no means a requirement though.

Anyway thanks for your work!

**Comment by simenkid** [comment]
Hi,
  Thanks for the advise, it is very useful. Also thanks for tracking this project, and please feel free to let me know if you have any feedback. I put all my heart to make it better. :D
