### ISSUE TITLE
Add gitter chat 

### ISSUE THREAD

**Issue by muoren** [lwmqn/mqtt-shepherd#4]
Having a [gitter](https://gitter.im)/[freenode](https://freenode.net/) channel might be a great way to get in touch and discuss some ideas.

**Comment by simenkid** [comment]
Hi muoren, I just open a room [here](https://gitter.im/lwmqn/Lobby?utm_source=share-link&utm_medium=link&utm_campaign=share-link) and you were invited as well. :D
